apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-reporting-config
  namespace: reporting
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SERVER_FORWARD_HEADERS_STRATEGY: framework
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_DATA_REDIS_HOST: redis-master
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  APP_SECURITY_CORS_ALLOWED_ORIGINS_0: https://portal.example.com
  APP_SECURITY_BROWSER_ALLOWED_ORIGINS_0: https://portal.example.com
