apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: banking-reporting-microservice
  namespace: reporting
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: banking-reporting-microservice
