apiVersion: v1
kind: Secret
metadata:
  name: banking-reporting-secret
  namespace: reporting
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-rw:5432/reporting
  SPRING_DATASOURCE_USERNAME: reporting_user
  SPRING_DATASOURCE_PASSWORD: change-me
  APP_SECURITY_JWT_SECRET_BASE64: change-me-base64
