apiVersion: v1
kind: Secret
metadata:
  name: {{ include "banking-reporting-microservice.fullname" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
